backend:
  name: github
  repo: anniinas/portfolio
  branch: main
  base_url: https://decap-oauth-portfolio-gh.anniina-sipria.workers.dev
  auth_endpoint: auth

media_folder: "public/images/uploads" # Kuvien sijainti
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blogi"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Otsikko", name: "title", widget: "string"}
      - {label: "Julkaisup채iv채", name: "date", widget: "datetime"}
      - {label: "P채채kuva", name: "image", widget: "image"}
      - {label: "Teksti", name: "body", widget: "markdown"}
