# local_backend: true # POISTA TÄMÄ KOMMENTTI LOKAALIA TESTAUSTA VARTEN (vaatii: npx decap-server)

backend:
  name: github
  repo: anniinas/portfolio
  branch: main
  base_url: https://decap-oauth-portfolio-gh.anniina-sipria.workers.dev
  auth_endpoint: auth

site_url: https://anniina-photo.pages.dev
display_url: https://anniina-photo.pages.dev

media_folder: "public/images/uploads" # Kuvien sijainti GitHubissa (suhteessa git-juureen)
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blogi"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Otsikko", name: "title", widget: "string"}
      - {label: "Julkaisupäivä", name: "date", widget: "datetime"}
      - {label: "Pääkuva", name: "image", widget: "image"}
      - {label: "Teksti", name: "body", widget: "markdown"}
